## This is the configuration file for WarpPoint
## If you don't know what you are doing I suggest
## you leave this file as is

## Changing this vaule will generate a new configuration file
ConfigurationVersion: 1

##
Permissions:
  warppoint.player:
    PrivateWarps: 5
    PublicTele: 1
    PublicSet: 2
    PublicMove: 0
    FactionTele: 1
    FactionMove: 1
    FactionSet: 2
  warppoint.vip:
    PrivateWarps: 10
    PublicTele: 1
    PublicSet: 2
    PublicMove: 0
    FactionTele: 1
    FactionMove: 1
    FactionSet: true
  warppoint.admin:
    PrivateWarps: true
    PublicTele: true
    PublicSet: true
    PublicMove: true
    FactionTele: true
    FactionMove: true
    FactionSet: true