name: WarpPoint
version: ${version}
main: net.lapismc.warppoint.WarpPoint
authors: [dart2112]
softdepend: [Factions]
description: The best way to warp
commands:
  warppoint:
    description: shows plugin info
  setwarp:
    description: sets a warp at your location
  delwarp:
    description: deletes a warp
  warp:
    description: sends you to a warp
