name: WarpPoint
version: ${version}
main: net.lapismc.warppoint.WarpPoint
authors: [dart2112]
softdepend: [Factions,Multiverse-Core]
description: The best way to warp
commands:
  warp:
    description: sends you to a warp
  setwarp:
    description: sets a warp at your location
  delwarp:
    description: deletes a warp
  warplist:
    description: shows the warps a player has access to
  warppoint:
    description: shows plugin info
